# Generated by Django 5.1.6 on 2025-02-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unverapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curs',
            options={'ordering': ['pk'], 'verbose_name': 'Curs', 'verbose_name_plural': 'Curs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['pk'], 'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
